Repository ruru-m07/ruru-ui, pull requests merged in 2024-09, with the labels that each got.

#68 feat(analytics): integrate posthog for web analytics
  apps/www/app/layout.tsx
  apps/www/app/providers.tsx
  apps/www/package.json
  apps/www/public/registry/components/avatar.json
  apps/www/public/registry/components/badge.json
  apps/www/public/registry/components/button.json
  packages/ui/src/components/avatar.tsx
  packages/ui/src/components/badge.tsx
  packages/ui/src/components/button.tsx
  pnpm-lock.yaml
Labels: enhancement

#70 fix(ui): resolve issue with PasswordInput component reveal icon
  apps/www/public/registry/components/input.json
  packages/ui/src/components/input.tsx
  pnpm-lock.yaml
Labels: bug, component: update

#71 Fix/scroll: Fixed visual glitch in Scrollable Select Component
  apps/www/components/selectLargeData.tsx
  apps/www/content/docs/components/select.mdx
  packages/ui/src/components/select.tsx
Labels: bug, docs: update, refactor: component

#77 feat(component): add accordion component and documentation
  apps/www/components/preview/accordion/accordionVariants.tsx
  apps/www/components/preview/index.tsx
  apps/www/content/docs/components/accordion.mdx
  apps/www/public/registry/components/accordion.json
  apps/www/public/registry/index.json
  apps/www/public/sitemap-0.xml
  apps/www/registry/ui.ts
  packages/ui/package.json
  packages/ui/src/components/accordion.tsx
  pnpm-lock.yaml
Labels: documentation, ci: pass, component: new
